name: Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v[0-9]+.[0-9]+.[0-9]+


jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v4

    - uses: docker/metadata-action@v5
      id: metadata
      with:
        images: |
          junlinwu/gallery-dl
        tags: |
          type=ref,event=tag
          type=raw,value=dev
          type=sha,format=long,prefix=
          type=raw,priority=500,value={{date 'YYYY.MM.DD'}}

    - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

   

    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: linux/arm/v6
